### PR TITLE
fixes links to github code examples

### PR DESCRIPTION
**Pull request by solegalli**
Hello, the links to the examples in the github repo are broken, probably because the examples were migrated as per this issue:
https://github.com/optuna/optuna/issues/2654

### CODE REVIEW

**Review by nzw0301 — APPROVED** [review]
Hi, @solegalli. Thank you for your pull request! It looks perfect to me.

**Review by hvy — APPROVED** [review]
Thanks a lot, LGTM!

**Comment by hvy** [comment]
Sorry, this repository is created for testing purpose. I'll propagate those fixes to the actual deployment.

**Comment by hvy** [comment]
They should've been fixed now. Please let me know if they aren't.

**Comment by solegalli** [comment]
Yep, the links are working now. Thank you!

**Pull request merged**
